sudo: false
language: node_js
node_js:
- stable
- 6
- 4
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  email: tonym@tonym.us
  provider: npm
  on:
    tags: true
  api_key:
    secure: biNEWs22IQhIjYCWpcF/FnRJUVyiViZwP8c9bhV/UpFWgajQbofOG1cBV8y9LoW39Aw9HsTJdSQtYOOcx6TXVFL8OhR4Q94UE91sc9iIOGXg7mnX/ZANFx8cAryXqx6ignE8MtvzNZLEVPKWpq5eGN2YhubkC/fTJZMV/HAjyKfKWT4JHf7rXMcLs3lYZpZVMuVDIU5Pi2ZKlvXGkhUjP3O65HznqHtyZ3Xi1q7m1eGqf8qoe9rtcpKrASXyOsNRJppLvtJFSjkvwtdMWWvGsSGJL4URxzZT5g8xbmAjAOleyxZR/PFt0xoz7NkXwpyI0qbvEIaHWdm/LyUrJRrU5devauaxjNGPa6qWEKx0KZ434/adjr1uCQScZWpMbDAOvNNTnO0zgaRjqUzpclQV7snozzOuKT7cereMGYejP1uixd/ZzmvteyXKSJ0vl4WY8vKz2RJSHouWAdKwwXO81n+m20jm1l46aGQcDG5DLJ1u8chxktfALakUZEN1nWfrLQZwcxKBc6hs0ncshoGgLp0zrpuel4mKod9Q7XveQpaxLt6yW5Mv7qnDcxLtM2TaVZ/R0KsGqn5fGGH5bijSD4ANnyQ/E3awlh7Al9ccE7bPXpy8iEELHruaRWN/378642uKikOSaqjih1mp8/RssA48rl9W5SmcXDB7VowpugM=
