sudo: false
language: node_js
node_js:
- stable
- 8
- 6
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
  - stage: npm release
    node_js: stable
    deploy:
      email: tonym@tonym.us
      provider: npm
      on:
        tags: true
      api_key:
        secure: L0e06ws84I1jT2Td6+mW9qcs85bgLpHHjmWoUoM+XLfr5/jo3stKvies4tOKTnqo1k8EzaAvKOmD2e1XSiTlE6iX5Vqf0sbaoBT7xk44Z15ygN/wbSSNPjiQfYizmA2pB7nz+HqDoNHlpk9ANHk4GjQghpaAUPNFmgvhnY25UYk4fVSNysUPkYsXLMA3gwBSFozKgayEEfuUbr2gSQSF8095tkQxRJzaBCGJTWLV/dYDA53ufAXzNedj7WmoYLjvfIJGzQDwON3+Cds10ostKzZLSRky2BuFGx7BLqAl0Zgn33pGtrCSXaRCJVGUeOoaAk5uG0IQobMyKFGgTxRVCk7ZbBug+NKinkjw2ts4ivGoGn2ILIYEd7q9mYdaSVaAUYU3Qc3ORgN8YxYZFVT9uKEkvA7p6KpxNYdekylQxwDuiIqdPH68sgsOx+8cbMEHxnGfAEItDgC+2LoSBe08zW600CgY+0Qe919KDeeDVwRAOHMeMHl4ss8KyFaTMvosTrS7hqOG1ifpMuUw1AZ+QuGueW7AAwjh4GC9ncjgWWbP7LleniavvpEzWk52SD998O/iD+95QNxu2KqJlroYFX6SRrpEng5brMNh6R9zl9efpIHHkBfjXSuIZ5iO9RbJ5E5nGOvsucZB8rKug4YRC56EsLrOcgDFYHIS7T85XX4=